# format = """
# [â•­â”€directoryâ¯](bold purple) $directory$rust$git_branch$git_status$package$golang$terraform$docker_context$python$docker_context$nodejs
# [â•°â”€cmdâ”€â”€â”€â”€â¯](bold cyan) """

[character]
success_symbol = "[âœ](bold purple)"
error_symbol = "[âœ—](bold red)"


[username]
style_user = "red bold"
style_root = "red bold"
#format = "[ğŸ•¸ at:]($style) "
#format = "[miles]($style) "
disabled = true 
show_always = true

[git_branch]
 #style = "red bold"

[python]
 #style = "blue bold"
